config/routes.rb
TimeChaser::Application.routes.draw do |map|
  resources :companies do
    resources :projects do
      resources :notes
      resources :tasks do
        resources :hours
      end
    end
  end
        

  root :to => "companies#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks, :class_name => "Task", :as => :taskable
  has_many :notes, :as => :noteable
  has_many :hours
  belongs_to :taskable, :polymorphic => true
  
  attr_accessor :is_subtask, :parent_task_id
  
  def parent_project
    if taskable_type == "Project"
      taskable
    elsif taskable_type == "Task"
      taskable.taskable
    else
      nil
    end
  end
  
  def items
    subtasks + notes
  end
  
  def subtask?
    taskable_type == "Task"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])
    @project = @task.parent_project
    @company = @project.company

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @company = Company.find(params[:company_id])
    @project = Project.find(params[:project_id])
    
    @is_subtask = (!params[:is_subtask].blank? && !params[:parent_task_id].blank?) ? true : false
    @parent_task_id = params[:parent_task_id] if @is_subtask
    
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @company = Company.find(params[:company_id])
    @project = Project.find(params[:project_id])
    taskable = (params[:task][:is_subtask].blank? || params[:task][:parent_task_id].blank?) ? @project : Task.find(params[:task][:parent_task_id].to_i)

    @task = Task.new(params[:task].merge(:taskable => taskable))

    respond_to do |format|
      if @task.save
        format.html { redirect_to([@company, @project, @task], :notice => 'Task was successfully created.') }
        format.xml  { render :xml => [@company, @project, @task], :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@company, @project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if @is_subtask %>
	<%= f.hidden_field :is_subtask, :value=> @is_subtask %>
	<%= f.hidden_field :parent_task_id, :value => @parent_task_id %>
<% end %>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :estimated_hours %><br />
    <%= f.text_field :estimated_hours %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li id="task_<%= task.id %>">
	<span class="task_desc"><%= task.desc %></span>
</li>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Desc</th>
    <th>Status</th>
    <th>Due date</th>
    <th>Estimated hours</th>
    <th>Url</th>
    <th>Order</th>
    <th>Parent</th>
    <th>Parent type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.desc %></td>
    <td><%= task.status %></td>
    <td><%= task.due_date %></td>
    <td><%= task.estimated_hours %></td>
    <td><%= task.url %></td>
    <td><%= task.order %></td>
    <td><%= task.parent_id %></td>
    <td><%= task.parent_type %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', company_project_tasks_path(@company, @project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @task.desc %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>

<p>
  <b>Estimated hours:</b>
  <%= @task.estimated_hours %>
</p>

<p>
  <b>Url:</b>
  <%= @task.url %>
</p>

<p>
  <b>Order:</b>
  <%= @task.order %>
</p>

<p>
  <b>Parent ID:</b>
  <%= @task.taskable_id %>
</p>

<p>
  <b>Parent type:</b>
  <%= @task.taskable_type %>
</p>


<%= link_to 'Edit', edit_company_project_task_path(@company, @project, @task) %> |
<%= link_to 'Back', (@task.subtask?) ? company_project_task_path(@company, @project, @task.taskable) : company_project_path(@company, @project) %>

<%  unless @task.subtask? %>
	<% unless @task.items.blank? %>
		<h2>Tasks &amp; Notes</h2>
		<ul>
		<%= render @task.items %>
		</ul>
	<% end %>
	<%= link_to 'New Task', new_company_project_task_path(@company, @project, {:is_subtask => 'true', :parent_task_id => @task.id}) unless @task.subtask?%>
<% end %>