config/routes.rb
TimeChaser::Application.routes.draw do |map|
  resources :companies do
    resources :projects do
      resources :notes
      resources :tasks do
        resources :hours
      end
    end
  end
        

  root :to => "companies#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  has_many :tasks, :as => :taskable
  has_many :notes, :as => :noteable

  def items
    tasks + notes
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    params[:choose_company] = params[:company_id]
    @company = Company.find(params[:company_id])
    @projects = @company.projects
    render :layout => false
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @company = @project.company
    params[:choose_company] = @company.id 
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @company = Company.find(params[:company_id])
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @company = @project.company
  end

  # POST /projects
  # POST /projects.xml
  def create
    @company = Company.find(params[:company_id])
    @project = Project.new(params[:project].merge(:company => @company))

    respond_to do |format|
      if @project.save
        format.html { redirect_to(([@company, @project]), :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])
    @company = @project.company

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(([@company, @project]), :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for ([@company, @project]) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<li><%= link_to project.title, company_project_path(@company, project) %></li>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Back', company_project_path(@company, @project) %>

app/views/projects/index.html.erb
<ul>
	<%  if @company && @company.id %><li><%= link_to '>> New Project', new_company_project_path(@company) %></li><% end %>
	<%= render @company.projects if @company %>
</ul>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', company_path(@company) %>

app/views/projects/show.html.erb
<div id="project_info_bar">
	<h1><%= @project.title %></h1>	
	<%= @project.url %>
	<%= @project.status %>
	<%= @project.due_date %>
	<%= link_to 'New Task', new_company_project_task_path(@company, @project) %>
</div>
<p id="notice"><%= notice %></p>


<% # link_to 'Edit', edit_company_project_path(@company, @project) %>
<% # link_to 'Back', company_path(@project.company) %>

<div id="task_list">
	<ul>
	<%= render @project.items %>
	</ul>
	
</div>